### ISSUE TITLE
Exception in thread Thread-3:

### ISSUE THREAD

**Issue by Akshaygala** [NuttyLogic/BSBolt#133]
I am getting an error while doing bsbolt call methylation.
Here is the error I get. I have attached my submitting script. Can someone help me with what I am doing wrong.

**Exception in thread Thread-3:
Traceback (most recent call last):
  File "/salilab/diva1/home/anaconda/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/salilab/diva1/home/anaconda/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/salilab/diva1/home/anaconda/anaconda3/lib/python3.8/multiprocessing/pool.py", line 592, in _handle_results
    cache[job]._set(i, obj)
  File "/salilab/diva1/home/anaconda/anaconda3/lib/python3.8/multiprocessing/pool.py", line 778, in _set
    self._error_callback(self._value)
  File "/wynton/home/pillailab/agala/.local/lib/python3.8/site-packages/bsbolt/CallMethylation/ProcessMethylationContigs.py", line 134, in methylation_process_error
    raise MethylationCallingError(error)
bsbolt.CallMethylation.ProcessMethylationContigs.MethylationCallingError: [Errno 20] Not a directory: '/wynton/scratch/agala/PTC_NC/Homo_sapiens.GRCh38.dna.primary_assembly.fa/1.pkl**
[bsboltcallmeth_launch.txt](https://github.com/NuttyLogic/BSBolt/files/8781736/bsboltcallmeth_launch.txt)
[bsboltcallmeth_work.txt](https://github.com/NuttyLogic/BSBolt/files/8781738/bsboltcallmeth_work.txt)
'

**Comment by Akshaygala** [comment]
I think I found the problem. I have not done indexing of the ref genome.
