### ISSUE TITLE
BSBolt Aggregate Matrix error

### ISSUE THREAD

**Issue by Akshaygala** [NuttyLogic/BSBolt#134]
This is my script: 

#!/bin/bash
. /etc/bashrc
module load CBI
module load Sali
module load samtools/1.9
module load anaconda
export PATH="${PATH}:~/.local/bin"
[BSBoltaggregate.bash.e32547.txt](https://github.com/NuttyLogic/BSBolt/files/8881069/BSBoltaggregate.bash.e32547.txt)
[BSBoltaggregate.txt](https://github.com/NuttyLogic/BSBolt/files/8881070/BSBoltaggregate.txt)

numcores="8"; minsitecvg="1"; minnumsamps="20"
keytsv="PTC_NC_samples.tsv"
numsamples="$(wc -l < "${keytsv}")"

outbase="Plex${numsamples}.bsbolt-grch38.sorted.CGmap-MQ20-BQ10-min1-max1000.sorted"
minsampfract="$( (echo 'scale=17'; echo "(${minnumsamps}+0.5)/${numsamples}") | bc)"

for ctx in CHG; do
        smpnamescommasep="$(awk -F $'\t' '{ printf("%s%s",                    (NR==1)?"":",",$1); }' < "${keytsv}")"
        mapfilescommasep="$(awk -F $'\t' '{ printf("%s%s.'"${ctx}"'map.gz",	  (NR==1)?"":",",$2); }' < "${keytsv}")"
        options="-t ${numcores} -S ${smpnamescommasep} -F ${mapfilescommasep}"
        options="${options} -min-coverage ${minsitecvg} -min-sample ${minsampfract}"
        optdesn="${ctx}-mincvg${minsitecvg}-minsamps${minnumsamps}"

        python3 -m bsbolt AggregateMatrix -count ${options} -O "${outbase}".aggcount-"${optdesn}".tsv
        python3 -m bsbolt AggregateMatrix        ${options} -O "${outbase}".aggfrmth-"${optdesn}".tsv
done

This is the error I get:
Exception in thread Thread-6:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/salilab/diva1/home/anaconda/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/wynton/home/pillailab/agala/.local/lib/python3.8/site-packages/bsbolt/Matrix/SiteAggregator.py", line 69, in collect_methylation_sites
    matrix_key = {site: count for count, site in enumerate(matrix_sites)}
  File "/wynton/home/pillailab/agala/.local/lib/python3.8/site-packages/bsbolt/Matrix/SiteAggregator.py", line 69, in <dictcomp>
    matrix_key = {site: count for count, site in enumerate(matrix_sites)}
MemoryError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/salilab/diva1/home/anaconda/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/salilab/diva1/home/anaconda/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/salilab/diva1/home/anaconda/anaconda3/lib/python3.8/multiprocessing/pool.py", line 592, in _handle_results
    cache[job]._set(i, obj)
  File "/salilab/diva1/home/anaconda/anaconda3/lib/python3.8/multiprocessing/pool.py", line 778, in _set
    self._error_callback(self._value)
  File "/wynton/home/pillailab/agala/.local/lib/python3.8/site-packages/bsbolt/Utils/UtilityFunctions.py", line 104, in propagate_error
    raise error
MemoryError

I had given ample memory for running the script but still cannot figure out what else is wrong. 
[PTC_NC_samples.txt](https://github.com/NuttyLogic/BSBolt/files/8881042/PTC_NC_samples.txt)

Here is an example of the file name, I am working on:
S8.sorted.deduped.CGmap-MQ20-BQ10-min1-max1000.sorted.CHGmap.gz

I have also attached the file from where it will obtain sample names and file names. I have changed the extension of the file from tsv to txt for uploading here

**Comment by NuttyLogic** [comment]
What version of BSBolt are you running?
